
name: CI

on:
  push:
    branches: [release]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Atualização do repositorio
        run: |
          git remote update
          git fetch 

  merge-master:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Ação de merge com master
        run: |
          git checkout origin/master
          git pull
          git merge origin/release --no-ff origin/master -m "Auto-merge release para prod"
          git push
          
  merge-dev:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Ação de merge com development
        run: |
          git checkout origin/development
          git pull
          git merge origin/release --no-ff origin/development -m "Auto-merge release para dev"
          git push
