
name: CI

on:
  push:
    branches: [release]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Início da build
        run: |
          echo Começando workflow!

  merge-master:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name : Configura usuario do commit
        run : |
          git config user.name "Workflow committer"
          git config user.email "<>"
      - name: Ação de merge com master
        run: |
          git fetch
          git checkout release
          git pull
          git checkout master
          git pull
          git merge -X theirs origin/release -s ours --allow-unrelated-histories -m "Auto-merge release para prod"
          git push
          
  merge-dev:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name : Configura usuario do commit
        run : |
          git config user.name "Workflow committer"
          git config user.email "<>"
      - name: Ação de merge com development
        run: |
          git fetch
          git checkout release
          git pull
          git checkout development
          git pull
          git merge -X theirs origin/release --allow-unrelated-histories -m "Auto-merge release para dev"
          git push
