
name: CI

on:
  push:
    branches: [release]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Início da build
        run: |
          echo Começando workflow!

  merge-master:
    runs-on: ubuntu-latest

    steps:
      - name : Configura usuario do commit
        uses: actions/checkout@v3
        run : |
          git config user.name "Workflow committer"
          git config user.email "<>"
      - name: Ação de merge com master
        uses: actions/checkout@v3
        run: |
          git fetch
          git checkout master
          git pull
          git merge origin/release --allow-unrelated-histories --no-ff master -m "Auto-merge release para prod"
          git push
          
  merge-dev:
    runs-on: ubuntu-latest

    steps:
      - name : Configura usuario do commit
        uses: actions/checkout@v3
        run : |
          git config user.name "Workflow committer"
          git config user.email "<>"
      - name: Ação de merge com development
        uses: actions/checkout@v3
        run: |
          git fetch
          git checkout development
          git pull
          git merge origin/release --allow-unrelated-histories --no-ff development -m "Auto-merge release para dev"
          git push
